version: '3'

services:
  app1:
    build: ./app1
    volumes:
      - ./app1:/var/www/html
    ports:
      - '80:80'
  app2:
    build: ./app2
    volumes:
      - ./app2:/var/www/html
    ports:
      - '81:80'